from . import hr_employee
from . import res_partner
from . import hr_department
from . import internal_consumption_config
from . import internal_consumption_audit
from . import internal_consumption_config_log
from . import pos_payment_method
from . import pos_order
from . import pos_session